version: "2"

services:

  sonarqube:
    image: sonarqube
    ports:
      - "8080:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarDb:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_exts:/opt/sonarqube/extensions
      - sonarqube_plugs:/opt/sonarqube/lib/bundled-plugins

  sonarDb:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarDb:/var/lib/postgresql

networks:
  sonarnet:
    driver: overlay
	
volumes:
  sonarDb:
    driver: azurefile
    driver_opts:
      share: "sonardb"
  sonarqube_conf:
    driver: azurefile
    driver_opts:
      share: "sonarqubeconf"
  sonarqube_data:
    driver: azurefile
    driver_opts:
      share: "sonarqubedata"
  sonarqube_exts:
    driver: azurefile
    driver_opts:
      share: "sonarqubeexts"
  sonarqube_plugs:
    driver: azurefile
    driver_opts:
      share: "sonarqubeplugs"